version: "3"
services:
  corona:
    build:
      context: .
      dockerfile: hotreload.Dockerfile
    container_name: corona-hotreload
    volumes:
      - ./vol:/data
      - ./app/static:/app/static
    ports:
      - 1919:1919
    networks:
      - corona
    env_file:
      - .env-docker.env

networks:
  corona:
