apiVersion: v1
kind: Service
metadata:
  name: {{ template "covid.name" . }}-{{ .Values.app.name }}
  labels:
    app: {{ template "covid.name" . }}
    run: {{ .Chart.Name }}-{{ .Values.app.name }}
    component: {{ .Values.app.name }}
    chart: {{ template "covid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.app.serviceType }}
  selector:
    app: {{ template "covid.name" . }}
    component: {{ .Values.app.name }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Chart.Name }}-{{ .Values.app.name }}-http
      protocol: TCP
      port: 1919
      targetPort: 1919
